// src/components/CuteSelect.tsx
import { useState, useRef, useEffect } from 'react';
import '../App.css';

export interface CuteSelectOption {
  label: string;
  value: string;
}

interface CuteSelectProps {
  value: string;
  options: (string | CuteSelectOption)[];
  onChange: (value: string) => void;
  className?: string;
  disabled?: boolean;
}

export function CuteSelect({ value, options, onChange, disabled = false }: CuteSelectProps) {
  const [isOpen, setIsOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // Normalize options to objects
  const normalizedOptions: CuteSelectOption[] = options.map(opt => 
    typeof opt === 'string' ? { label: opt, value: opt } : opt
  );

  const selectedOption = normalizedOptions.find(opt => opt.value === value);
  const displayLabel = selectedOption ? selectedOption.label : value || 'Select...';

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleSelect = (val: string) => {
    if (disabled) return;
    onChange(val);
    setIsOpen(false);
  };

  return (
    <div 
      className={`cute-select-container ${isOpen ? 'open' : ''} ${disabled ? 'disabled' : ''}`} 
      ref={containerRef}
    >
      <button
        type="button"
        className="cute-select-trigger"
        onClick={() => !disabled && setIsOpen(!isOpen)}
        disabled={disabled}
      >
        <span className="current-value">{displayLabel}</span>
        <span className="arrow">▼</span>
      </button>

      {isOpen && (
        <div className="cute-select-menu">
          {normalizedOptions.map((option) => (
            <button
              key={option.value}
              type="button"
              className={`cute-option ${option.value === value ? 'selected' : ''}`}
              onClick={() => handleSelect(option.value)}
            >
              {option.label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// src/components/CuteSelect.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  type Option = string | { label: string; value: string };

  interface Props {
    value: string;
    options: Option[];
    onChange: (value: string) => void;
    disabled?: boolean;
  }

  let { value, options, onChange, disabled = false }: Props = $props();

  let isOpen = $state(false);
  let containerRef: HTMLDivElement;

  // Derived state for normalized options
  let normalizedOptions = $derived(
    options.map((opt) => (typeof opt === 'string' ? { label: opt, value: opt } : opt))
  );

  let selectedOption = $derived(normalizedOptions.find((opt) => opt.value === value));
  let displayLabel = $derived(selectedOption ? selectedOption.label : value || 'Select...');

  function handleClickOutside(event: MouseEvent) {
    if (containerRef && !containerRef.contains(event.target as Node)) {
      isOpen = false;
    }
  }

  function handleSelect(val: string) {
    if (disabled) return;
    onChange(val);
    isOpen = false;
  }

  // Window listener for click outside
  // Svelte special element <svelte:window> makes this cleaner
</script>

<svelte:window onclick={handleClickOutside} />

<div
  class="cute-select-container"
  class:open={isOpen}
  class:disabled={disabled}
  bind:this={containerRef}
>
  <button
    type="button"
    class="cute-select-trigger"
    onclick={() => !disabled && (isOpen = !isOpen)}
    {disabled}
  >
    <span class="current-value">{displayLabel}</span>
    <span class="arrow">▼</span>
  </button>

  {#if isOpen}
    <div class="cute-select-menu">
      {#each normalizedOptions as option (option.value)}
        <button
          type="button"
          class="cute-option"
          class:selected={option.value === value}
          onclick={() => handleSelect(option.value)}
        >
          {option.label}
        </button>
      {/each}
    </div>
  {/if}
</div>
